### Create new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "admin@test.com",
    "password": "12345"
}

### Sign in a exiting user
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "admin@test.com",
    "password": "12345"
}


### Signing out an user
POST    http://localhost:3000/auth/signout


### Get currently signed user
GET http://localhost:3000/auth/whoami


### Get user by id
GET http://localhost:3000/auth/1

### Get user by email
GET http://localhost:3000/auth?email=xxx@xxx.com

### Remove user from database
DELETE http://localhost:3000/auth/22

### Update a user
PATCH http://localhost:3000/auth/12
Content-Type: application/json

{
    "email": "xxx@xxx.com"
}

